// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Intern struct {
	ID            string  `json:"id"`
	FirstName     string  `json:"first_name"`
	LastName      string  `json:"last_name"`
	PhoneNumber   *string `json:"phone_number,omitempty"`
	Email         string  `json:"email"`
	Password      string  `json:"password"`
	ProviderID    *string `json:"provider_id,omitempty"`
	Provider      *string `json:"provider,omitempty"`
	AvatarURL     *string `json:"avatar_url,omitempty"`
	Status        *string `json:"status,omitempty"`
	ApplicationID *int32  `json:"application_id,omitempty"`
	RememberToken *string `json:"remember_token,omitempty"`
	CreatedAt     *string `json:"created_at,omitempty"`
	UpdatedAt     *string `json:"updated_at,omitempty"`
}

type Mutation struct {
}

type NewInternInput struct {
	FirstName     string  `json:"first_name"`
	LastName      string  `json:"last_name"`
	PhoneNumber   *string `json:"phone_number,omitempty"`
	Email         string  `json:"email"`
	Password      string  `json:"password"`
	ProviderID    *string `json:"provider_id,omitempty"`
	Provider      *string `json:"provider,omitempty"`
	AvatarURL     *string `json:"avatar_url,omitempty"`
	ApplicationID *int32  `json:"application_id,omitempty"`
}

type Query struct {
}
